import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api, unwrap } from "../api/client.js";

export const GradebookPage = () => {
  const { courseTrackId } = useParams(); const [data, setData] = useState(null); const [search, setSearch] = useState(""); const [error, setError] = useState("");
  const load = async () => { try { setError(""); setData(unwrap(await api.get(`/api/v1/admin/courses/${courseTrackId}/gradebook`, { params: { search, limit: 25 } }))); } catch (e) { setError(e.response?.data?.error?.message || "Unable to load the Gradebook."); } };
  useEffect(() => { load(); }, [courseTrackId]);
  const addComment = async (studentId) => { const comment = window.prompt("Teacher comment"); if (!comment) return; try { await api.post(`/api/v1/admin/courses/${courseTrackId}/students/${studentId}/comments`, { comment, visibility: "student_visible" }); await load(); } catch (e) { setError(e.response?.data?.error?.message || "Unable to add the comment."); } };
  return <section className="gradebook-page"><header className="admin-page-heading"><div><Link to={`/courses/${courseTrackId}/content`}>← Course content</Link><p className="admin-kicker">Medium administration</p><h2>Gradebook Lite</h2></div></header><form onSubmit={(event) => { event.preventDefault(); load(); }}><label>Student search <input onChange={(event) => setSearch(event.target.value)} value={search} /></label><button type="submit">Filter</button></form>{error ? <p className="admin-error">{error}</p> : null}{data ? <table><thead><tr><th>Student</th><th>Completion</th><th>Quiz grade</th><th>Course total</th><th>Status</th><th>Pending</th><th>Comment</th></tr></thead><tbody>{data.items.map((row) => <tr key={row.student.id}><td>{row.student.name}<small>{row.student.email}</small></td><td>{row.completion.percentage}%</td><td>{row.quizzes.length ? row.quizzes.map((quiz) => quiz.percentage === undefined ? "—" : `${quiz.percentage}%`).join(", ") : "—"}</td><td>{row.overallGrade === null ? "—" : `${row.overallGrade}%`}</td><td>{row.passFail}</td><td>{row.pendingGrades ? "Yes" : "No"}</td><td><button onClick={() => addComment(row.student.id)} type="button">Add comment</button></td></tr>)}</tbody></table> : <p className="resource-empty">Loading Gradebook…</p>}</section>;
};
