import { useCallback, useEffect, useState } from "react";
import { api, unwrap } from "../api/client.js";
import { ResourcePicker } from "../components/ResourcePicker.jsx";

const blank = { category: "lesson_pdf", displayName: "", description: "", visibility: "private", accessPolicy: "course_enrolled", file: null };
const bytes = (value) => value ? `${(Number(value) / 1024 / 1024).toFixed(2)} MB` : "—";
export const ResourceLibraryPage = () => {
  const [items, setItems] = useState([]); const [categories, setCategories] = useState([]); const [form, setForm] = useState(blank); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [resources, registry] = await Promise.all([api.get("/api/v1/admin/resources", { params: { search, limit: 100 } }), api.get("/api/v1/admin/resource-categories")]); setItems(unwrap(resources).items || []); setCategories(unwrap(registry)); } catch (requestError) { setError(requestError.response?.data?.error?.message || "Unable to load Resource Library"); } }, [search]);
  useEffect(() => { load(); }, [load]);
  const category = categories.find((item) => item.code === form.category);
  const change = ({ target }) => setForm((current) => ({ ...current, [target.name]: target.files ? target.files[0] : target.value }));
  const selectCategory = ({ target }) => { const chosen = categories.find((item) => item.code === target.value); setForm((current) => ({ ...current, category: target.value, visibility: chosen?.defaultVisibility || "private", accessPolicy: chosen?.defaultAccessPolicy || "admin_only" })); };
  const upload = async (event) => { event.preventDefault(); if (!form.file) return setError("Choose a file to upload."); setBusy(true); setError(""); setNotice(""); try { const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); const result = unwrap(await api.post("/api/v1/admin/resources", body, { onUploadProgress: (progress) => setNotice(`Uploading ${Math.round((progress.loaded / (progress.total || 1)) * 100)}%`) })); setNotice(result.duplicateId ? "Uploaded. An identical active resource already exists." : "Resource uploaded securely."); setForm(blank); await load(); } catch (requestError) { setError(requestError.response?.data?.error?.message || "Unable to upload resource"); } finally { setBusy(false); } };
  const archive = async (id) => { try { await api.post(`/api/v1/admin/resources/${id}/archive`); await load(); } catch (requestError) { setError(requestError.response?.data?.error?.message || "Unable to archive resource"); } };
  return <section className="downloadable-resources"><div className="admin-page-heading"><div><p className="admin-kicker">Secure files</p><h2>Resource Library</h2><p>Private learning files are only delivered by authorized API requests.</p></div></div><form className="resource-form" onSubmit={upload}><h3>Upload resource</h3><label>Category<select name="category" onChange={selectCategory} value={form.category}>{categories.map((item) => <option key={item.code} value={item.code}>{item.code}</option>)}</select></label><label>Display name<input name="displayName" onChange={change} value={form.displayName} /></label><label className="resource-description-field">Description<textarea name="description" onChange={change} value={form.description} /></label><label>Visibility<select disabled={!category?.publicAllowed} name="visibility" onChange={change} value={form.visibility}><option value="private">Private</option><option value="public">Public</option></select></label><label>Access policy<select disabled={!category?.publicAllowed} name="accessPolicy" onChange={change} value={form.accessPolicy}><option value="public">Public</option><option value="authenticated">Authenticated</option><option value="course_enrolled">Course enrolled</option><option value="premium">Premium</option><option value="admin_only">Admin only</option></select></label><label className="resource-file-field">File<input accept={category?.allowedMimeTypes?.join(",")} name="file" onChange={change} type="file" /></label>{category ? <p>Allowed: {category.allowedMimeTypes.join(", ")} · max {bytes(category.maxSizeBytes)}</p> : null}<button disabled={busy} type="submit">{busy ? "Uploading…" : "Upload resource"}</button></form>{error ? <p className="admin-error">{error}</p> : null}{notice ? <p>{notice}</p> : null}<label>Search resources<input onChange={(event) => setSearch(event.target.value)} placeholder="Display name or original filename" value={search} /></label><div className="resource-table-wrap"><table><thead><tr><th>Name</th><th>Category</th><th>Type / size</th><th>Access</th><th>Status</th><th>Links</th><th>Action</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.displayName}</strong><small>{item.originalFilename}</small></td><td>{item.category}</td><td>{item.mimeType}<small>{bytes(item.sizeBytes)}</small></td><td>{item.visibility} · {item.accessPolicy}</td><td>{item.status}</td><td>{item.linkedItemCount}</td><td>{["active", "ready"].includes(item.status) ? <button onClick={() => archive(item.id)} type="button">Archive</button> : "—"}</td></tr>)}</tbody></table>{!items.length ? <p className="resource-empty">No resources match this filter.</p> : null}</div><details><summary>Resource Picker foundation</summary><ResourcePicker allowedCategories={["course_thumbnail", "course_banner", "lesson_image", "video_thumbnail", "site_asset"]} onSelect={(item) => setNotice(`Selected ${item.displayName}; this picker is ready for the Course Builder.`)} /></details></section>;
};
